// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface Bomb
{
	SetBomb Owner {
		get;
		set;
	}
	int LifeTime {
		get;
		set;
	}
	BombFire Fire {
		get;
		set;
	}

	int Power {
		get;
		set;
	}
	void setProperties(SetBomb owner,int power,int lifeTime);
}


