// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface BombFire: Attackable
{
	GameObject Onwer {
		get;
		set;
	}
	int LifeTime {
		get;
		set;
	}

	void setProperties(GameObject onwer,int lifeTime);
}


