// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public interface Distroyable
{
	int Blood 
	{
		get;
		set;
	}

	//add for invincible
//	bool isDistoryalbe {
//		get;
//		set;
//	}

	void attackBy(Attackable source);
	void distroy();
}


